"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var estudiante_model_1 = require("./estudiante.model");
var asignatura_model_1 = require("./asignatura.model");
var sunnydale_model_1 = require("./sunnydale.model");
var e1 = new estudiante_model_1.Estudiante('Xabi', 'ciencias');
var e2 = new estudiante_model_1.Estudiante('Alberto', 'letras');
var e3 = new estudiante_model_1.Estudiante('Jasone', 'letras');
var e4 = new estudiante_model_1.Estudiante('Ander', 'ciencias');
var e5 = new estudiante_model_1.Estudiante('Amaia', 'ciencias');
var e6 = new estudiante_model_1.Estudiante('Ali', 'letras');
var a1 = new asignatura_model_1.Asignatura('Matematicas', 'ciencias');
var a2 = new asignatura_model_1.Asignatura('Lenguaje', 'letras');
var a3 = new asignatura_model_1.Asignatura('Tecnologia', 'ciencias');
var a4 = new asignatura_model_1.Asignatura('Historia', 'letras');
var a5 = new asignatura_model_1.Asignatura('Biologia', 'ciencias');
var a6 = new asignatura_model_1.Asignatura('Filosofia', 'letras');
var sunnydale = new sunnydale_model_1.Sunnydale([e1, e2, e3, e4, e5, e6], [a1, a2, a3, a4, a5, a6]);
sunnydale.globales();
